# Copy this file to keystore.properties (DO NOT COMMIT keystore.properties)
# GitHub Actions will generate keystore.properties automatically during builds.

# Path to your keystore file on disk (on GitHub runner we place it under app/)
storeFile=app/vrca-release.jks

# Keystore password
storePassword=CHANGE_ME

# Key alias inside the keystore
keyAlias=vrca

# Key password
keyPassword=CHANGE_ME

githubPat=ghp_xxxxxxxxxxxxxxxxxxxx
githubOwner=your-github-username
githubRepo=Chatbox-VRC-A
